# Generated by Django 3.0.3 on 2020-02-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldschema',
            name='data_type',
            field=models.CharField(choices=[('character', 'character'), ('text', 'text'), ('integer', 'integer'), ('float', 'float'), ('boolean', 'boolean'), ('date', 'date'), ('foreign_key', 'foreign_key')], editable=False, max_length=16),
        ),
    ]
